spring:
  application:
    name: app
  datasource:
    url: jdbc:postgresql://localhost:5432/app
    username: test
    password: test

security:
  secret-key: bXlzdXBlcnNlY3JldGtleWZvcmp3dHRoYXRpY29tcG9zZWlubXloZWFk

springdoc:
  swagger-ui:
    path: /swagger-ui
